---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: server
    run_list:
      - recipe[ircd-ratbox::server]
    attributes:
  - name: services
    run_list:
      - recipe[ircd-ratbox::services]
    attributes:

